title = BattleTanks
author = Xlvisuals
description = BattleTanks is a 3D multiplayer Tron-style tank shooter
allowed_mapgens = singlenode
default_mapgen = singlenode
disabled_settings = creative_mode, enable_damage
release = 1
